version: v1.2.0

serve:
  public:
    base_url: http://localhost:4433
    cors:
      enabled: true
  admin:
    base_url: http://localhost:4434

selfservice:
  default_browser_return_url: http://localhost:4455/
  allowed_return_urls:
    - http://localhost:4455

  methods:
    code: # or link
      enabled: true
    password:
      enabled: true
      config:
        identifier_similarity_check_enabled: false
        haveibeenpwned_enabled: false
    oidc:
      enabled: true
      config:
        providers:
          - id: google
            provider: google
            client_id: ...
            client_secret: ...
            mapper_url: file:///etc/config/kratos/google_mapper.jsonnet
            scope:
              - openid
              - email
              - profile
            requested_claims:
              id_token:
                email:
                  essential: true
                given_name:
                  essential: true
                family_name:
                  essential: true
    passkey:
      enabled: true
      config:
        rp:
          display_name: ory-poc
          id: localhost
          origins:
            - http://localhost:4455

  flows:
    recovery:
      enabled: true
      use: code # Defines which method is used, one of 'code' or 'link'.
      notify_unknown_recipients: false # Defines if the system sends attempted recovery notifications to unregistered addresse
      ui_url: http://localhost:8362/recovery
      after:
        hooks:
          - hook: revoke_active_sessions

    error:
      ui_url: http://localhost:4455/error

    settings:
      ui_url: http://localhost:4455/settings
      # required_aal: highest_available

    logout:
      after:
        default_browser_return_url: http://localhost:4455/login

    login:
      ui_url: http://localhost:4455/login
      after:
        hooks:
          - hook: require_verified_address

    verification:
      ui_url: http://localhost:8362/verification
      use: code # Defines which method is used, one of 'code' or 'link'.
      enabled: true

      notify_unknown_recipients: false

    registration:
      ui_url: http://localhost:4455/registration
      after:
        password:
          hooks:
            - hook: session
        oidc:
          hooks:
            - hook: session
log:
  format: text
  leak_sensitive_values: true

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

oauth2_provider:
  url: http://hydra:4445

feature_flags:
  use_continue_with_transitions: true
